# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.box = "ubuntu/focal64" 
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.57.10"
    web.vm.synced_folder "./web", "/var/www/html/"
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install nginx -y
    SHELL
  end
  
  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.box = "ubuntu/focal64"
    app.vm.network "private_network", ip: "192.168.57.11"
    app.vm.provision "shell", privileged: false, inline: <<-SHELL
      sudo apt-get update
      apt-get -y install build-essential libssl-dev
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      source ~/.nvm/nvm.sh
      nvm install node
      npm install express
      npm install -g nodemon
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.box = "ubuntu/focal64"
    db.vm.network "private_network", ip: "192.168.57.12"
  end
  
end
