version: "3.9"
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: log
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - network-backend
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: log
    depends_on:
      - db
    links:
      - db
    ports:
      - 9000:9000
    networks:
      - network-backend
      - network-frontend

networks:
  network-frontend:
  network-backend:
  